#! /bin/bash

# Configurable parameters
# If the feature needs different parameters values, they can be set in
# the file {feature}/defaults, which is sourced a little later on.  This
# defaults file SHOULD NOT TOUCH ANY OTHER VARIABLE than these, or hell
# may break loose.

TAR_OWNER=root:0
TAR_GROUP=root:0

# End of configurable parameters

here=${DEPLOY_DIR:-$(pwd)}
scriptdir=$(cd $(dirname $(realpath $0)); pwd)

save_args="$*"
upload=true
verbose=false
while [ $# -gt 0 ]; do
    case "$1" in
	-n )
	    upload=false
	    ;;
	-v )
	    verbose=true
	    ;;
	* )
	    break
	    ;;
    esac
    shift
done

feature=$1; shift
hosts="$*"

if ! tpage < /dev/null 2> /dev/null; then
    cat >&2 <<EOF
Template Toolkit is required.
On a Debian based distribution, install libtemplate-perl
On a RPM base distribution, install perl-Template-Toolkit
(available through CPAN with the package Template)
EOF
    exit 1
fi

if [ -z "$feature" ]; then
    echo 'No feature name given'
    exit 1
fi

if echo "$feature" | egrep -q '^_|[/[:space:]]'; then
    echo 'Underscore (_), spaces and slashes (/) not permitted in feature names'
    exit 1
fi

if cd $here/$feature; then
    abshere=$(pwd)
    tpagerc=
    if [ -f tpagerc ]; then
	tpagerc=$abshere/tpagerc
    fi
    if [ -f HOSTS -a -f README ]; then
	if [ -z "$hosts" ]; then
	    hosts=$(cat HOSTS | grep -v '^#' | cut -f1 -d:)
	    hosts=$(for h in $hosts; do
			if echo $h | grep '^\?' > /dev/null; then
			    h=$(echo $h | cut -f2 -d'?')
			    if getent hosts $h > /dev/null; then
				echo $h
			    fi
			else
			    echo $h
			fi
		    done)
	fi

	# Phase 0: Checks
	echo >&2 "===== Phase 0: Checks"
	declare -A fqdnhosts
	fqdnhosts=()
	for h in $hosts; do
	    if ! ( echo $h | grep -q -e "\\." ); then
		if hh=$(grep -e "^$h\\." HOSTS) && ( echo "$h" | grep ' ' ); then
		    echo >&2 "'$h' isn't unique enough"
		    exit 1
		fi
	    else
		hh=${h//./\\.}
		hh=$(egrep -e "^\\??$hh(:|\$)" HOSTS | sed -e 's|^\?||')
	    fi
	    finalhost=$(echo $hh | cut -f1 -d:)
	    currenthost=$(echo $hh | cut -f2 -d:)
	    if [ -z "$currenthost" ]; then currenthost=$finalhost; fi
	    if [ -z "$finalhost" ]; then
		echo >&2 "Error: $h doesn't exist in $feature/HOSTS"
		exit 1
	    fi
	    fqdnhosts[$currenthost]=$(echo ${fqdnhosts[$currenthost]} ${finalhost})
	done

	if $upload; then
	    bail_out=/bin/false
	    for currenthost in ${!fqdnhosts[*]}; do
		remacct=${REMACCT:+${REMACCT}\@}

		if ! ssh -o ConnectTimeout=2 ${REMACCT:+${REMACCT}\@}${currenthost} 'exit 0'; then
		    echo >&2 "Failed: ssh ${REMACCT:+${REMACCT}\@}${currenthost}"
		    bail_out=/bin/true
		fi
	    done
	    if $bail_out; then
		if [ -z "${REMACCT}" ]; then
		    echo >&2 "You may want to try setting REMACCT to your username on that host:"
		    echo >&2 ""
		    echo >&2 "    REMACCT=username $0 $save_args"
		fi
		exit 1
	    fi
	fi

	staging=/tmp/deploy.$$

	if [ -f defaults ]; then
	    . ./defaults
	fi

	if ! mkdir $staging; then
	    echo >&2 "Error: couldn't create directory $staging"
	    exit 2
	fi

	tpage_extra=""
	for pp in $abshere/../preamble.tt2 $abshere/preamble.tt2; do
	    if [ -f "$pp" ]; then
		tpage_extra="$tpage_extra --pre_process='$pp'"
	    fi
	done
	for pp in $abshere/postamble.tt2 $abshere/../postamble.tt2; do
	    if [ -f "$pp" ]; then
		tpage_extra="$tpage_extra --post_process='$pp'"
	    fi
	done

	# Phase 1: Prepare files to be transfered
	echo >&2 "===== Phase 1: Preparing files"
	for currenthost in ${!fqdnhosts[*]}; do
	    data=$staging/$currenthost-data
	    control=$staging/$currenthost-control
	    tarball=$control/deploy.$feature.tar.gz
	    rm -f $tarball

	    if ! mkdir $data; then
		echo >&2 "Error: couldn't create directory $data"
		exit 2
	    fi

	    if ! mkdir $control; then
		echo >&2 "Error: couldn't create directory $control"
		exit 2
	    fi

	    tpage_cmd=$(echo tpage \
			     "--define hosts='${fqdnhosts[$currenthost]}'" \
			     "--define feature='$feature'" \
			     "--define data='$data'" \
			     "--define control='$control'" \
			     "--define verbose='$verbose'")
	    if [ -n "$tpagerc" ]; then
		tpage_cmd="TPAGERC=$tpagerc $tpage_cmd"
	    fi

	    # Phase 1.1: Run the pre-copy script
	    if [ -x pre-copy ]; then
		( cd $data; \
		  HOSTS="${fqdnhosts[$currenthost]}" FEATURE="$feature" \
		       DATA="$data" CONTROL="$control" SOURCE="$abshere" \
		       VERBOSE="$verbose" \
		       $abshere/pre-copy )
	    fi

	    # Phase 1.2: Copy common files into staging directory
	    cp README $data/README.$feature
	    
	    # Phase 1.3: Copy common source files into staging directory
	    if [ -d src ]; then
		( cd src; tar -cf - $(git ls-tree -r --name-only master) ) | \
		    ( cd $data; tar -xpf - )
	    fi

	    # Phase 1.4: Copy host specific files into staging directory
	    for h in $( for x in $currenthost ${fqdnhosts[$currenthost]}; do \
			    echo $x; \
			done | sort | uniq ); do
		if [ -d $h ]; then
		    ( cd $h; tar -cf - $(git ls-tree -r --name-only master) ) | \
			( cd $data; tar -xpf - )
		fi
	    done

	    # Phase 1.5: process template source files in staging directory
	    # and replace them with their respective result
	    find $data -name '*.tt2' -type f | \
		while read src; do
		    src=$(dirname "$src")/$(basename "$src")
		    dst=$(dirname "$src")/$(basename "$src" .tt2)
		    if [ "$src" != "$dst" ]; then
			eval "$tpage_cmd $tpage_extra '$src'" > "$dst"
			chmod --reference="$src" "$dst"
			rm "$src"
		    fi
		done

	    # Phase 1.7: Run post-copy
	    if [ -x post-copy ]; then
		( cd $data; \
		  HOSTS="${fqdnhosts[$currenthost]}" FEATURE="$feature" \
		       DATA="$data" CONTROL="$control" SOURCE="$abshere" \
		       VERBOSE="$verbose" \
		       $abshere/post-copy )
	    fi

	    # Phase 1.8: Create the host specific pre-deployment script
	    if [ -f pre-deploy.tt2 ]; then
		src=pre-deploy.tt2
		dst=$control/pre-deploy.$feature
		eval "$tpage_cmd $tpage_extra '$src'" > "$dst"
		chmod a+x $dst
	    elif [ -x pre-deploy ]; then
		dst=$control/pre-deploy.$feature
		cp pre-deploy $dst
		chmod a+x $dst
	    fi

	    # Phase 1.9: Create the host specific post-deployment script
	    if [ -f post-deploy.tt2 ]; then
		src=post-deploy.tt2
		dst=$control/post-deploy.$feature
		eval "$tpage_cmd $tpage_extra '$src'" > "$dst"
		chmod a+x $dst
	    elif [ -x post-deploy ]; then
		dst=$control/post-deploy.$feature
		cp post-deploy $dst
		chmod a+x $dst
	    fi

	    # Phase 1.10: Create the local tarball and remove staging directory
	    (
		cd $data
		tar --owner=$TAR_OWNER --group=$TAR_GROUP -czf $tarball *
	    )

	    # Phase 1.20: Create the deployment scripts
	    for src in $scriptdir/_host_helpers/*.tt2; do
		dst=$control/$(basename $src .tt2).$feature
		eval "$tpage_cmd $tpage_extra '$src'" > $dst
		chmod a+x $dst
	    done

	    # Phase 1.21: Copy deploy-remove from REMOVE
	    if [ -f REMOVE ]; then
		dst=$control/deploy-remove.$feature.txt
		cp REMOVE $dst
	    fi

	    # Phase 1.99: Cleanup
	    rm -rf $data
	done

	if $upload; then
	    # Phase 2: Copy tarballs to intended hosts
	    echo >&2 "===== Phase 2: Copying files to remote hosts"
	    successhosts=""
	    for currenthost in ${!fqdnhosts[*]}; do
		control=$staging/$currenthost-control

		echo -n "Copying deployment tarball and deployment files to $currenthost..."
		if scp -q $control/* ${REMACCT:+${REMACCT}\@}${currenthost}:/tmp/; then
		    echo done
		    successhosts=$(echo $successhosts $currenthost)
		else
		    echo FAIL
		fi
		rm -rf $control
	    done

	    # Phase 3: Final instructions
	    echo >&2 "===== Phase 3: Final instructions"
	    if [ -n "$successhosts" ]; then
		cat <<EOF
You will find the tarball "deploy.$feature.tar.gz" in /tmp/ on each of
EOF
		echo $successhosts
		cat <<EOF

Please verify that the files to be deployed are what you expect.  You do so
by running the following on each host and studying the resulting diff output:

	/tmp/deploy-diff.$feature

If you're satisfied with what you see, please deploy as follows:

	/tmp/deploy.$feature

and perform post deployment tasks as follows (this will also clean away all
deployment files if the post deployment tasks themselves didn't fail):

	/tmp/deploy-post.$feature

EOF
	    else
		cat <<EOF
Copying failed on all hosts.  Please fix the problem, or if someone else
was deploying at the same time as you, simply wait a moment
EOF
	    fi
	    rmdir $staging
	else
	    echo >&2 "No upload selected, tarballs and deploy scripts preserved:"
	    for currenthost in ${!fqdnhosts[*]}; do
		control=$staging/$currenthost-control
		echo >&2
		echo >&2 "${control}:"
		ls $control >&2
	    done
	fi
    else
	echo $feature lacking HOSTS and README
	exit 1
    fi
fi
